image: nexus.esphere.local:5000/ledacy:275

stages:
  - prepare
  - check
  - cypress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: prepare
  tags:
    - NONPROD
  script: npm install
  except:
    - tags
    - triggers

lint:
  stage: check
  tags:
    - NONPROD
  script: npm run lint
  except:
    - tags
    - triggers

test:
  stage: check
  tags:
    - NONPROD
  script: npm run test
  except:
    - tags
    - triggers

tsc:
  stage: check
  tags:
    - NONPROD
  script: npm run tsc
  except:
    - tags
    - triggers

cypress:
  stage: cypress
  script: npm run cypress-ci
  tags:
    - cypress
  variables:
    GIT_CLEAN_FLAGS: -fx -e node_modules/
  except:
    - tags
    - triggers
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - cypress/screenshots
      - cypress/videos
