on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.npm
          key: rjsghskjdfg=${{ hashFiles('package-lock.json') }}
          restore-keys: rjsghskjdfg=
      - run: npm ci
  cypress:
    runs-on: ubuntu-16.04
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          key: rjsghskjdfg=${{ hashFiles('package-lock.json') }}
          path: node_modules
      - uses: cypress-io/github-action@v1
        with:
          start: npm start
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v1
        if: ${{ job.status == 'failure' }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: ${{ job.status == 'failure' }}
        with:
          name: cypress-videos
          path: cypress/videos
